
all:
	@echo 
	@echo "  VERSE supports Linux, Mac OS X. Please choose the correct Makefile to build VERSE."
	@echo 
	@echo "  For building in Linux, please run ' make -f Makefile.Linux '."
	@echo "  For building in Mac OS X, please run ' make -f Makefile.MacOS '."
	@echo
	@echo "  The default compiler is gcc; you may change the compiler by editing the makefile."
	@echo
